<?xml version = '1.0'?>
<ROWSET>
<ROW num="1" SELECTFLAG="0" name="">
<ID>12</ID>
<NAME>需求确认</NAME>
<NOTE>从[录入状态]到[需求确认]</NOTE>
<SRCID>1</SRCID>
<DESTID>2</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="2" SELECTFLAG="0" name="">
<ID>23</ID>
<NAME>设计完成</NAME>
<NOTE>从[需求确认]到[设计完成]</NOTE>
<SRCID>2</SRCID>
<DESTID>3</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="3" SELECTFLAG="0" name="">
<ID>34</ID>
<NAME>开发完成</NAME>
<NOTE>从[设计完成]到[开发完成]</NOTE>
<SRCID>3</SRCID>
<DESTID>4</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY23</ACTMW>
<TRKTYP>1</TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="4" SELECTFLAG="0" name="">
<ID>45</ID>
<NAME>测试通过</NAME>
<NOTE>从[开发完成]到[测试通过]</NOTE>
<SRCID>4</SRCID>
<DESTID>5</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="5" SELECTFLAG="0" name="">
<ID>56</ID>
<NAME>操作手册提交</NAME>
<NOTE>从[测试通过]到[操作手册已提交]</NOTE>
<SRCID>5</SRCID>
<DESTID>6</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY431</ACTMW>
<TRKTYP>1</TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="6" SELECTFLAG="0" name="">
<ID>67</ID>
<NAME>培训完毕</NAME>
<NOTE>从[操作手册已提交]到[培训完毕]</NOTE>
<SRCID>6</SRCID>
<DESTID>7</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY45</ACTMW>
<TRKTYP>1</TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="7" SELECTFLAG="0" name="">
<ID>78</ID>
<NAME>实施完毕</NAME>
<NOTE>从[培训完毕]到[实施完毕]</NOTE>
<SRCID>7</SRCID>
<DESTID>8</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY56</ACTMW>
<TRKTYP>1</TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="8" SELECTFLAG="0" name="">
<ID>71</ID>
<NAME>退回录入</NAME>
<NOTE>从[培训完毕]到[录入状态]</NOTE>
<SRCID>7</SRCID>
<DESTID>1</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="9" SELECTFLAG="0" name="">
<ID>21</ID>
<NAME>取消确认</NAME>
<NOTE>从[需求确认]到[录入状态]</NOTE>
<SRCID>2</SRCID>
<DESTID>1</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="10" SELECTFLAG="0" name="">
<ID>54</ID>
<NAME>测试未通过</NAME>
<NOTE>从[测试通过]到[开发完成]</NOTE>
<SRCID>5</SRCID>
<DESTID>4</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="11" SELECTFLAG="0" name="">
<ID>65</ID>
<NAME>重新提交手册</NAME>
<NOTE>从[操作手册已提交]到[测试通过]</NOTE>
<SRCID>6</SRCID>
<DESTID>5</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="12" SELECTFLAG="0" name="">
<ID>28</ID>
<NAME>实施完毕</NAME>
<NOTE>从[需求确认]到[实施完毕]</NOTE>
<SRCID>2</SRCID>
<DESTID>8</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY16</ACTMW>
<TRKTYP>1</TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="13" SELECTFLAG="0" name="">
<ID>82</ID>
<NAME>需求确认</NAME>
<NOTE>从[实施完毕]到[需求确认]</NOTE>
<SRCID>8</SRCID>
<DESTID>1</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="14" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="15" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="16" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="17" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="18" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="19" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="20" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
</ROWSET>
