<?xml version = '1.0'?>
<ROWSET>
<ROW num="1" SELECTFLAG="0" name="">
<ID>12</ID>
<NAME>部门审批通过</NAME>
<NOTE>从[已录入]到[确定]</NOTE>
<SRCID>1</SRCID>
<DESTID>2</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="2" SELECTFLAG="0" name="">
<ID>21</ID>
<NAME>部门审批退回</NAME>
<NOTE>从[确定]到[已录入]</NOTE>
<SRCID>2</SRCID>
<DESTID>1</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="3" SELECTFLAG="0" name="">
<ID>23</ID>
<NAME>人事审批通过</NAME>
<NOTE>从[确定]到[审批]</NOTE>
<SRCID>2</SRCID>
<DESTID>3</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="4" SELECTFLAG="0" name="">
<ID>32</ID>
<NAME>部门直接发布</NAME>
<NOTE>从[审批]到[确定]</NOTE>
<SRCID>2</SRCID>
<DESTID>4</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="5" SELECTFLAG="0" name="">
<ID>34</ID>
<NAME>人事发布</NAME>
<NOTE>从[人事审批]到[发布]</NOTE>
<SRCID>3</SRCID>
<DESTID>4</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="6" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="7" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="8" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="9" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="10" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="11" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="12" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="13" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="14" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="15" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="16" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="17" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="18" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="19" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
<ROW num="20" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TRKTYP></TRKTYP>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL11></COL11>
</ROW>
</ROWSET>
