<?xml version = '1.0'?>
<ROWSET>
<ROW num="1" SELECTFLAG="0" name="">
<ID>1</ID>
<NAME>客户确认</NAME>
<NOTE>从[录入状态]到[客户已确认]</NOTE>
<SRCID>1</SRCID>
<DESTID>2</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="2" SELECTFLAG="0" name="">
<ID>2</ID>
<NAME>开发完成</NAME>
<NOTE>从[客户已确认]到[开发完成]</NOTE>
<SRCID>2</SRCID>
<DESTID>3</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="3" SELECTFLAG="0" name="">
<ID>3</ID>
<NAME>手册提交</NAME>
<NOTE>从[开发完成]到[手册已提交]</NOTE>
<SRCID>3</SRCID>
<DESTID>4</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="4" SELECTFLAG="0" name="">
<ID>4</ID>
<NAME>培训完成</NAME>
<NOTE>从[手册提交]到[培训完成]</NOTE>
<SRCID>4</SRCID>
<DESTID>5</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="5" SELECTFLAG="0" name="">
<ID>5</ID>
<NAME>已经正常实施</NAME>
<NOTE>从[培训完成]到[正常实施]</NOTE>
<SRCID>5</SRCID>
<DESTID>6</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="6" SELECTFLAG="0" name="">
<ID>6</ID>
<NAME>结束</NAME>
<NOTE>从[正常实施]到[结束]</NOTE>
<SRCID>6</SRCID>
<DESTID>7</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="7" SELECTFLAG="0" name="">
<ID>7</ID>
<NAME>强制取消</NAME>
<NOTE>从[录入状态]到[强制取消]</NOTE>
<SRCID>1</SRCID>
<DESTID>8</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="8" SELECTFLAG="0" name="">
<ID>8</ID>
<NAME>强制取消</NAME>
<NOTE>从[客户确认]到[强制取消]</NOTE>
<SRCID>2</SRCID>
<DESTID>8</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="9" SELECTFLAG="0" name="">
<ID>9</ID>
<NAME>强制取消</NAME>
<NOTE>从[开发完成]到[强制取消]</NOTE>
<SRCID>3</SRCID>
<DESTID>8</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="10" SELECTFLAG="0" name="">
<ID>10</ID>
<NAME>强制取消</NAME>
<NOTE>从[操作手册提交]到[强制取消]</NOTE>
<SRCID>4</SRCID>
<DESTID>8</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="11" SELECTFLAG="0" name="">
<ID>11</ID>
<NAME>强制取消</NAME>
<NOTE>从[已培训]到[强制取消]</NOTE>
<SRCID>5</SRCID>
<DESTID>8</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="12" SELECTFLAG="0" name="">
<ID>12</ID>
<NAME>强制取消</NAME>
<NOTE>从[正常实施]到[强制取消]</NOTE>
<SRCID>6</SRCID>
<DESTID>8</DESTID>
<WHERE></WHERE>
<ACTMW>TRK_SAMODIFY</ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="13" SELECTFLAG="0" name="">
<ID>27</ID>
<NAME>结束</NAME>
<NOTE>从[客户已确认]到[结束]</NOTE>
<SRCID>2</SRCID>
<DESTID>7</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="14" SELECTFLAG="0" name="">
<ID>67</ID>
<NAME>结束</NAME>
<NOTE>从[已经正常实施]到[结束]</NOTE>
<SRCID>6</SRCID>
<DESTID>7</DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="15" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="16" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="17" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="18" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="19" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
<ROW num="20" SELECTFLAG="0" name="">
<ID></ID>
<NAME></NAME>
<NOTE></NOTE>
<SRCID></SRCID>
<DESTID></DESTID>
<WHERE></WHERE>
<ACTMW></ACTMW>
<TOROL></TOROL>
<TOUSR></TOUSR>
<COL10></COL10>
</ROW>
</ROWSET>
